spring:
  application:
    name: cloud-provider-nacos204
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR}
        namespace: ${NACOS_NAMESPACE}
        group: ${NACOS_GROUP}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
        metadata:
          isjoin: ${MESH_SWITCHER_MESH}
          deploy: ${DEPLOY_TYPE}
          svcname: ${PAAS_NS}:${MESH_SVC_NAME:cloud-provider-nacos204}
          pod-name: ${HOSTNAME}
          paas-name: ${MESH_SVC_NAME:cloud-provider-nacos204}
          paas-ns: ${PAAS_NS}
          service-type: SpringCloud