spring:
  application:
    name: nacos-dubbo-demo-provider
demo:
  service:
    version: 1.0.0
    group: vm-nacos-dubbo

dubbo:
  protocol:
    port: 20880
    name: dubbo
  registry:
    address: nacos://10.7.164.31:8848?username=z4ZPEKEAuyEE&password=QDxn1VSnpWD8
    parameters:
      namespace: 72950d308774
      ignoreCheckKeys: username,password
  provider:
    parameters:
      isjoin: true
      deploy: vm
      svcname: dev:nacos-dubbo-demo-provider
      paas-name: vm-nacos-dubbo-demo-provider
      paas-ns: dev
      service-type: Dubbo


