spring:
  application:
    name: nacos-dubbo-demo-provider
demo:
  service:
    version: 2.0.0
    group: vm-nacos-dubbo

dubbo:
  protocol:
    port: 20880
    name: dubbo
  registry:
    address: nacos://10.7.164.43:8848?username=Ipqgl6ABhIf6&password=uQKGYER5VKOC
    parameters:
      namespace: b096fb131f94
      group: junxia
      ignoreCheckKeys: username,password
  provider:
    parameters:
      isjoin: false
      deploy: vm
      svcname: dev:nacos-dubbo-demo-provider
      paas-name: vm-nacos-dubbo-demo-provider
      paas-ns: dev
      service-type: Dubbo
logging:
  level:
    com:
      alibaba:
        nacos: trace
