spring:
  application:
    name: springcloud-demo-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.31.226:8848
        namespace: tenant-gfg47nzk3tgs
        group: DEFAULT_GROUP
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
        metadata:
#          pod-name: ${HOSTNAME}
          paas-name: ${MESH_SVC_NAME:springcloud-demo-consumer}
          paas-ns: wjx
          service-type: SpringCloud
          isjoin: true
          deploy: container
          svcname: wjx:${MESH_SVC_NAME:springcloud-demo-consumer}
#模拟故障模拟，设置延时
feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000