spring:
  application:
    name: cloud-consumer-nacos204
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR}
        namespace: ${NACOS_NAMESPACE}
        group: ${NACOS_GROUP}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
        metadata:
          pod-name: ${HOSTNAME}
          paas-name: ${MESH_SVC_NAME:cloud-consumer-nacos204}
          paas-ns: ${PAAS_NS}
          service-type: SpringCloud
          isjoin: ${MESH_SWITCHER_MESH}
          deploy: ${DEPLOY_TYPE}
          svcname: ${PAAS_NS}:${MESH_SVC_NAME:cloud-consumer-nacos204}
#模拟故障模拟，设置延时
feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000